In [4]:
import pandas as pd
import numpy as np
dataset = pd.read_csv("E:/JDE/olist/olist_order_reviews_dataset.csv")

In [5]:
from textblob import TextBlob

In [6]:
def translating(comment):
    try:
        translated_comment = TextBlob(comment).translate(from_lang='pt-BR', to='en')
    except:
        translated_comment = comment
    return translated_comment

In [7]:
dataset['translate_comment_message'] = dataset['review_comment_message'].apply(lambda x: translating(x))

# for i, comment in enumerate(dataset['review_comment_message']):
#     try:
#         translated_comment = TextBlob(comment).translate(from_lang='pt-BR', to='en')
#     except:
#         translated_comment = comment
#     dataset.loc[i, 'translate_comment_message'] = str(translated_comment)
    # if i == 7:
    #     break

In [8]:
dataset.loc[:7]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,translate_comment_message
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59,NaN
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13,NaN
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24,NaN
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06,"(I, , r, e, c, e, i, v, e, d, , w, e, l, l, ..."
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53,"(C, o, n, g, r, a, t, u, l, a, t, i, o, n, s, ..."
5,15197aa66ff4d0650b5434f1b46cda19,b18dcdf73be66366873cd26c5724d1dc,1,NaN,NaN,2018-04-13 00:00:00,2018-04-16 00:39:37,NaN
6,07f9bee5d1b850860defd761afa7ff16,e48aa0d2dcec3a2e87348811bcfdf22b,5,NaN,NaN,2017-07-16 00:00:00,2017-07-18 19:30:34,NaN
7,7c6400515c67679fbee952a7525281ef,c31a859e34e3adac22f376954e19b39d,5,NaN,NaN,2018-08-14 00:00:00,2018-08-14 21:36:06,NaN